### PR TITLE
New methods

### PR DESCRIPTION
**Pull request by BeeHiveJava**
Hi redpois0n,

I saw this repository and it was quite useful, but I added some more features and did some clean-ups. Just see if you like them.

Here's what I did:
- Reordered methods in NativeWindow
- Added new methods:

In NativeWindow:
- setVisible(boolean visible)
- setRectangle(Rectangle rect)
- setTitle(String title)
- toString method

In WindowUtils:
- getVisibleWindows()
- getByTitle(String title)

In WindowUtils.User32:
- FindWindowA(String lpClassName, String lpWindowName)
- MoveWindow(int hWnd, int X, int Y, int nWidth, int nHeight, boolean bRepaint)
- SetWindowTextA(int hWnd, String text)

I'm not too sure what you wanted to do with comments, so I followed the guidelines of your comments, if you want them improved, just ask.

Cheers,

U2 For Me

### CODE REVIEW

**Comment by wille** [comment]
thanks

**Comment by wille** [comment]
Why I didn't include SetWindowText

> SetWindowText function
> Changes the text of the specified window's title bar (if it has one). If the specified window is a control, the text of the control is changed. **However, SetWindowText cannot change the text of a control in another application.**

[Source](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633546%28v=vs.85%29.aspx)

**Comment by BeeHiveJava** [comment]
Hey,

I entirely reprogrammed it including documentation. It respects JNA more and includes proper methods for isMinimized and isMaximized. I cleaned up all the files and followed standard Java interface conventions. If you like you can clone it, but if you'd like to continue on this repository, I completely understand. If the latter is the case, please tell me, because everytime I add a major feature I'll keep you updated with it.

Thanks,

U2 For Me

**Comment by BeeHiveJava** [comment]
Bump

I added more methods, have a look here: https://github.com/U2ForMeJava/nativewindowlib
Would you like me to continue contributing here? Or just leave it and continue on my own repository?

Cheers,

U2 For Me

**Pull request merged**
